#!/bin/bash
# Скрипт применения исправлений к main.py

echo "🔧 Применение исправлений к main.py..."

# 1. Убираем кнопки и отправляем отдельное сообщение
sed -i 's/if message_id_to_process:/if message_id_to_process:\n                    # Сначала пробуем убрать кнопки (если таймер ещё не убрал)\n                    try:\n                        await bot.edit_message_reply_markup(\n                            chat_id=ADMIN_GROUP_ID,\n                            message_id=message_id_to_process,\n                            reply_markup=None\n                        )\n                        logger.info(f"{log_prefix} Кнопки удалены")\n                    except Exception as e_rm:\n                        logger.debug(f"{log_prefix} Не удалось удалить кнопки: {e_rm}")\n\n                    # Отправляем ОТДЕЛЬНОЕ сообщение с результатом (reply на карточку ДЗ)\n                    try:\n                        await bot.send_message(\n                            chat_id=ADMIN_GROUP_ID,\n                            text=final_admin_notification,\n                            reply_to_message_id=message_id_to_process,\n                            parse_mode=None\n                        )\n                        logger.info(f"{log_prefix} Результат отправлен в админ-чат")\n                    except Exception as e_admin_notify:\n                        logger.error(f"{log_prefix} Ошибка отправки: {e_admin_notify}")\n                else:\n                    # Если нет message_id, просто отправляем сообщение\n                    try:\n                        await bot.send_message(\n                            chat_id=ADMIN_GROUP_ID,\n                            text=final_admin_notification,\n                            parse_mode=None\n                        )\n                        logger.info(f"{log_prefix} Результат отправлен (без reply)")\n                    except Exception as e_admin_notify:\n                        logger.error(f"{log_prefix} Ошибка: {e_admin_notify}")\n                # ЗАКОММЕНТИРОВАНО СТАРОЕ:/g' main.py

echo "✅ Исправления применены!"
